set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86)
set(CMAKE_GENERATOR_PLATFORM Win32)

set(CMAKE_C_COMPILER cl.exe)
set(CMAKE_CXX_COMPILER cl.exe)

set(CMAKE_C_FLAGS "/arch:IA32")
set(CMAKE_CXX_FLAGS "/arch:IA32")
set(CMAKE_LINK_FLAGS "/MACHINE:X86")